version: "3.7"

networks:
  doraemon-finance-network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: doraemon-finance-web
    container_name: doraemon-finance-web-c
    restart: unless-stopped
    ports:
      - 8080:3001
    networks:
      - doraemon-finance-network
